#!/usr/bin/env python
import os
import sys

if 'brainer' not in sys.path:
    sys.path.append(os.path.join(
        os.path.dirname(os.path.realpath(__file__)), '..'))

from brainer.client import main

main()
